apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/auth-mongo-depl.yaml
      - ./infra/k8s/nats-depl.yaml
      - ./infra/k8s/tickets-depl.yaml
      - ./infra/k8s/tickets-mongo-depl.yaml
      - ./infra/k8s/client-depl.yaml
      - ./infra/k8s/ingress-srv.yaml
      - ./infra/k8s/orders-depl.yaml
      - ./infra/k8s/orders-mongo-depl.yaml
      - ./infra/k8s/payments-depl.yaml
      - ./infra/k8s/payments-mongo-depl.yaml
build:
  local:
    push: false
  artifacts:
    - image: ehtesham-dev/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ehtesham-dev/client
      context: ../client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
          - src: '**/*.css'
            dest: .
    - image: ehtesham-dev/tickets
      context: .
      docker:
        dockerfile: tickets/Dockerfile
      sync:
        manual:
          - src: 'tickets/src/**/*.ts'
            dest: .
    - image: ehtesham-dev/orders
      context: .
      docker:
        dockerfile: orders/Dockerfile
      sync:
        manual:
          - src: 'orders/src/**/*.ts'
            dest: .
    - image: ehtesham-dev/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ehtesham-dev/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .